#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Shark
version:      1.0.0
version_from: Shark.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
